#include <base/kf_types.hxx>
#include <base/kf_base.hxx>

static KF_RESULT kKFResult[] = {
    KF_OK, KF_NO,

    KF_ERROR, KF_ABORT,
    KF_PENDING, KF_UNEXPECTED,
    KF_SHUTDOWN, KF_TIMEOUT,
    KF_ACCESS_DENIED, KF_OUT_OF_MEMORY,
    KF_BUF_TOO_SMALL, KF_RE_ENTRY,
    KF_INIT_ERROR, KF_IO_ERROR,
    KF_NO_INTERFACE, KF_NO_MATCH,

    KF_INVALID_ARG, KF_INVALID_PTR,
    KF_INVALID_DATA, KF_INVALID_STATE,
    KF_INVALID_INPUT, KF_INVALID_OUTPUT,
    KF_INVALID_OBJECT, KF_INVALID_OPERATION,

    KF_NOT_FOUND, KF_NOT_SUPPORTED,
    KF_NOT_INITIALIZED, KF_NOT_IMPLEMENTED,

    KF_NETWORK_DATA_INVALID, KF_NETWORK_JSON_INVALID, KF_NETWORK_SOCKET_INVALID,
    KF_NETWORK_CONNECT_FAIL, KF_NETWORK_CONNECT_TIMEOUT, KF_NETWORK_TOO_MAY_REQUESTS,
    KF_NETWORK_SEND_FAIL, KF_NETWORK_RECV_FAIL,
    KF_NETWORK_PROTOCOL_ERROR, KF_NETWORK_CRYPT_ERROR,
#ifdef KF_USE_MEDIA
    KF_MEDIA_ERR_UNKNOWN, KF_MEDIA_ERR_EXTERNAL, KF_MEDIA_ERR_HARDWARE,
    KF_MEDIA_ERR_UNAVAILABLE, KF_MEDIA_ERR_UNSUPPORTED, KF_MEDIA_ERR_CANCELLED,
    KF_MEDIA_ERR_STOPPED, KF_MEDIA_ERR_CLOSED, KF_MEDIA_ERR_ALLOC,
    KF_MEDIA_ERR_PARSE, KF_MEDIA_ERR_PROBE, KF_MEDIA_ERR_SEEK,

    KF_MEDIA_ERR_RENDER_HARDWARE, KF_MEDIA_ERR_RENDER_DISPLAY, KF_MEDIA_ERR_RENDER_PROCESSING,
    KF_MEDIA_ERR_RENDER_OPEN, KF_MEDIA_ERR_RENDER_START, KF_MEDIA_ERR_RENDER_PAUSE,
    KF_MEDIA_ERR_RENDER_STOP, KF_MEDIA_ERR_RENDER_RATE,

    KF_MEDIA_UNSUPPORTED_CODEC, KF_MEDIA_UNSUPPORTED_SERVICE,
    KF_MEDIA_UNSUPPORTED_BYTESTREAM, KF_MEDIA_UNSUPPORTED_COLOR_SPACE,
    KF_MEDIA_UNSUPPORTED_COLOR_FORMAT, KF_MEDIA_UNSUPPORTED_FORMAT_CHANGE,

    KF_MEDIA_BAD_REQUEST, KF_MEDIA_WRONG_STATE, KF_MEDIA_STATE_PENDING,
    KF_MEDIA_BUF_TOO_SMALL, KF_MEDIA_ALREADY_EXISTS,

    KF_MEDIA_FIXED_STREAMS, KF_MEDIA_END_OF_STREAM,
    KF_MEDIA_FLUSH_NEEDED, KF_MEDIA_NEED_MORE_DATA,
    KF_MEDIA_FORMAT_CHANGED, KF_MEDIA_FORMAT_CHANGED_BREAK,

    KF_MEDIA_INVALID_DATA, KF_MEDIA_INVALID_FILE, KF_MEDIA_INVALID_TYPE,
    KF_MEDIA_INVALID_COLOR, KF_MEDIA_INVALID_CODEC, KF_MEDIA_INVALID_CLOCK,
    KF_MEDIA_INVALID_INPUT, KF_MEDIA_INVALID_INDEX, KF_MEDIA_INVALID_BUFFER,
    KF_MEDIA_INVALID_FORMAT, KF_MEDIA_INVALID_STREAM, KF_MEDIA_INVALID_HEADER,
    KF_MEDIA_INVALID_SAMPLE, KF_MEDIA_INVALID_OBJECT, KF_MEDIA_INVALID_PROFILE,
    KF_MEDIA_INVALID_POSITION, KF_MEDIA_INVALID_TIMESTAMP,
    KF_MEDIA_INVALID_DESCRIPTOR, KF_MEDIA_INVALID_PRIVATE_DATA,

    KF_MEDIA_NOT_INITIALIZED, KF_MEDIA_NOT_ACCEPTING,
    KF_MEDIA_NOT_WRITABLE, KF_MEDIA_NOT_SEEKABLE,
    KF_MEDIA_NOT_FOUND, KF_MEDIA_NOT_SET,

    KF_MEDIA_SCHEME_HANDLER_NOT_FOUND, KF_MEDIA_STREAM_HANDLER_NOT_FOUND,
    KF_MEDIA_CODEC_FILTER_NOT_FOUND, KF_MEDIA_DECODER_NOT_FOUND, KF_MEDIA_ENCODER_NOT_FOUND,

    KF_MEDIA_NO_ANY_BUFFER, KF_MEDIA_NO_SERVICE,
    KF_MEDIA_NO_STREAM, KF_MEDIA_NO_SAMPLE,
    KF_MEDIA_NO_TIMESTAMP, KF_MEDIA_NO_DURATION,
    KF_MEDIA_NO_CLOCK, KF_MEDIA_NO_TIME_SOURCE,

    KF_MEDIA_NO_SOURCE, KF_MEDIA_NO_CODEC, KF_MEDIA_NO_SINK,
    KF_MEDIA_FAILED_SOURCE, KF_MEDIA_FAILED_CODEC, KF_MEDIA_FAILED_SINK,
#endif
    KF_RESULT_RESERVED
};

static const char* kKFResultText[] = {
    "KF_OK", "KF_NO",

    "KF_ERROR", "KF_ABORT",
    "KF_PENDING", "KF_UNEXPECTED",
    "KF_SHUTDOWN", "KF_TIMEOUT",
    "KF_ACCESS_DENIED", "KF_OUT_OF_MEMORY",
    "KF_BUF_TOO_SMALL", "KF_RE_ENTRY",
    "KF_INIT_ERROR", "KF_IO_ERROR",
    "KF_NO_INTERFACE", "KF_NO_MATCH",

    "KF_INVALID_ARG", "KF_INVALID_PTR",
    "KF_INVALID_DATA", "KF_INVALID_STATE",
    "KF_INVALID_INPUT", "KF_INVALID_OUTPUT",
    "KF_INVALID_OBJECT", "KF_INVALID_OPERATION",

    "KF_NOT_FOUND", "KF_NOT_SUPPORTED",
    "KF_NOT_INITIALIZED", "KF_NOT_IMPLEMENTED",

    "KF_NETWORK_DATA_INVALID", "KF_NETWORK_JSON_INVALID", "KF_NETWORK_SOCKET_INVALID",
    "KF_NETWORK_CONNECT_FAIL", "KF_NETWORK_CONNECT_TIMEOUT", "KF_NETWORK_TOO_MAY_REQUESTS",
    "KF_NETWORK_SEND_FAIL", "KF_NETWORK_RECV_FAIL",
    "KF_NETWORK_PROTOCOL_ERROR", "KF_NETWORK_CRYPT_ERROR",
#ifdef KF_USE_MEDIA
    "KF_MEDIA_ERR_UNKNOWN", "KF_MEDIA_ERR_EXTERNAL", "KF_MEDIA_ERR_HARDWARE",
    "KF_MEDIA_ERR_UNAVAILABLE", "KF_MEDIA_ERR_UNSUPPORTED", "KF_MEDIA_ERR_CANCELLED",
    "KF_MEDIA_ERR_STOPPED", "KF_MEDIA_ERR_CLOSED", "KF_MEDIA_ERR_ALLOC",
    "KF_MEDIA_ERR_PARSE", "KF_MEDIA_ERR_PROBE", "KF_MEDIA_ERR_SEEK",

    "KF_MEDIA_ERR_RENDER_HARDWARE", "KF_MEDIA_ERR_RENDER_DISPLAY", "KF_MEDIA_ERR_RENDER_PROCESSING",
    "KF_MEDIA_ERR_RENDER_OPEN", "KF_MEDIA_ERR_RENDER_START", "KF_MEDIA_ERR_RENDER_PAUSE",
    "KF_MEDIA_ERR_RENDER_STOP", "KF_MEDIA_ERR_RENDER_RATE",

    "KF_MEDIA_UNSUPPORTED_CODEC", "KF_MEDIA_UNSUPPORTED_SERVICE",
    "KF_MEDIA_UNSUPPORTED_BYTESTREAM", "KF_MEDIA_UNSUPPORTED_COLOR_SPACE",
    "KF_MEDIA_UNSUPPORTED_COLOR_FORMAT", "KF_MEDIA_UNSUPPORTED_FORMAT_CHANGE",

    "KF_MEDIA_BAD_REQUEST", "KF_MEDIA_WRONG_STATE", "KF_MEDIA_STATE_PENDING",
    "KF_MEDIA_BUF_TOO_SMALL", "KF_MEDIA_ALREADY_EXISTS",

    "KF_MEDIA_FIXED_STREAMS", "KF_MEDIA_END_OF_STREAM",
    "KF_MEDIA_FLUSH_NEEDED", "KF_MEDIA_NEED_MORE_DATA",
    "KF_MEDIA_FORMAT_CHANGED", "KF_MEDIA_FORMAT_CHANGED_BREAK",

    "KF_MEDIA_INVALID_DATA", "KF_MEDIA_INVALID_FILE", "KF_MEDIA_INVALID_TYPE",
    "KF_MEDIA_INVALID_COLOR", "KF_MEDIA_INVALID_CODEC", "KF_MEDIA_INVALID_CLOCK",
    "KF_MEDIA_INVALID_INPUT", "KF_MEDIA_INVALID_INDEX", "KF_MEDIA_INVALID_BUFFER",
    "KF_MEDIA_INVALID_FORMAT", "KF_MEDIA_INVALID_STREAM", "KF_MEDIA_INVALID_HEADER",
    "KF_MEDIA_INVALID_SAMPLE", "KF_MEDIA_INVALID_OBJECT", "KF_MEDIA_INVALID_PROFILE",
    "KF_MEDIA_INVALID_POSITION", "KF_MEDIA_INVALID_TIMESTAMP",
    "KF_MEDIA_INVALID_DESCRIPTOR", "KF_MEDIA_INVALID_PRIVATE_DATA",

    "KF_MEDIA_NOT_INITIALIZED", "KF_MEDIA_NOT_ACCEPTING",
    "KF_MEDIA_NOT_WRITABLE", "KF_MEDIA_NOT_SEEKABLE",
    "KF_MEDIA_NOT_FOUND", "KF_MEDIA_NOT_SET",

    "KF_MEDIA_SCHEME_HANDLER_NOT_FOUND", "KF_MEDIA_STREAM_HANDLER_NOT_FOUND",
    "KF_MEDIA_CODEC_FILTER_NOT_FOUND", "KF_MEDIA_DECODER_NOT_FOUND", "KF_MEDIA_ENCODER_NOT_FOUND",

    "KF_MEDIA_NO_ANY_BUFFER", "KF_MEDIA_NO_SERVICE",
    "KF_MEDIA_NO_STREAM", "KF_MEDIA_NO_SAMPLE",
    "KF_MEDIA_NO_TIMESTAMP", "KF_MEDIA_NO_DURATION",
    "KF_MEDIA_NO_CLOCK", "KF_MEDIA_NO_TIME_SOURCE",

    "KF_MEDIA_NO_SOURCE", "KF_MEDIA_NO_CODEC", "KF_MEDIA_NO_SINK",
    "KF_MEDIA_FAILED_SOURCE", "KF_MEDIA_FAILED_CODEC", "KF_MEDIA_FAILED_SINK",
#endif
    "KF_RESULT_RESERVED"
};

const char* KFTypeGetResultString(KF_RESULT result)
{
    for (int i = 0; i < KF_ARRAY_COUNT(kKFResult); i++) {
        if (kKFResult[i] == result)
            return kKFResultText[i];
    }
    return "";
}